image: kieluniphysik/texlive

stages:
    - build

compile_thesis:
    stage: build
    script:
        - latexmk -xelatex -latexoption="--shell-escape" thesis.tex
        - cd cv
        - latexmk -xelatex cv.tex
        - mv cv.pdf ..
        - cv ..
    artifacts:
        paths:
            - thesis.pdf
            - cv.pdf

#compile_talk:
#    stage: build
#    script:
#        - cd talks
#        - latexmk -xelatex master_thesis_talk.tex
#        - mv master_thesis_talk.pdf ../
#    artifacts:
#        paths:
#            - master_thesis_talk.pdf