image: kieluniphysik/texlive

stages:
    - build

compile_thesis:
    stage: build
    script:
        - latexmk -xelatex -latexoption="--shell-escape" thesis.tex
    artifacts:
        paths:
            - thesis.pdf

compile_thesis_online:
    stage: build
    script:
        - latexmk -xelatex -latexoption="--shell-escape" thesis_online.tex
    artifacts:
        paths:
            - thesis_online.pdf
            
compile_cv:
    stage: build
    script:
        - cd cv && latexmk -xelatex cv.tex && cd ..
        - mv cv/cv.pdf cv.pdf
    artifacts:
        paths:
            - cv.pdf

compile_eigenanteil:
    stage: build
    script:
        - cd eigenanteil && latexmk -xelatex eigenanteil.tex && cd ..
        - mv eigenanteil/eigenanteil.pdf eigenanteil.pdf
    artifacts:
        paths:
            - eigenanteil.pdf

compile_talk:
    stage: build
    script:
        - cd talk
        - latexmk -xelatex talk.tex
        - mv talk.pdf ../
    artifacts:
        paths:
            - talk.pdf