image: kieluniphysik/texlive

stages:
    - build

compile_thesis:
    stage: build
    script:
        - latexmk -xelatex -latexoption="--shell-escape" thesis.tex
    artifacts:
        paths:
            - thesis.pdf
            
compile_cv:
    stage: build
    script:
        - cd cv && latexmk -xelatex cv.tex && cd ..
        - mv cv/cv.pdf cv.pdf
    artifacts:
        paths:
            - cv.pdf

compile_eigenanteil:
    stage: build
    script:
        - cd eigenanteil && latexmk -xelatex eigenanteil.tex && cd ..
        - mv eigenanteil/eigenanteil.pdf eigenanteil.pdf
    artifacts:
        paths:
            - eigenanteil.pdf

#compile_talk:
#    stage: build
#    script:
#        - cd talks
#        - latexmk -xelatex master_thesis_talk.tex
#        - mv master_thesis_talk.pdf ../
#    artifacts:
#        paths:
#            - master_thesis_talk.pdf